-- MySQL Script generated by MySQL Workbench
-- Tue Sep 23 19:01:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nhn_academy_14
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nhn_academy_14
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nhn_academy_14` DEFAULT CHARACTER SET utf8 ;
USE `nhn_academy_14` ;

-- -----------------------------------------------------
-- Table `nhn_academy_14`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhn_academy_14`.`Players` ;

CREATE TABLE IF NOT EXISTS `nhn_academy_14`.`Players` (
  `player_id` INT NOT NULL,
  `nickname` VARCHAR(30) NULL,
  `email` VARCHAR(100) NULL,
  `joined_at` DATETIME NOT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`player_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nhn_academy_14`.`Payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhn_academy_14`.`Payments` ;

CREATE TABLE IF NOT EXISTS `nhn_academy_14`.`Payments` (
  `payment_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `payment_method` ENUM('CARD', 'BANK', 'CASH', 'STORE') NOT NULL,
  `paid_at` DATETIME NOT NULL,
  `item_description` VARCHAR(100) NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`, `player_id`),
  UNIQUE INDEX `payment_id_UNIQUE` (`payment_id` ASC) VISIBLE,
  INDEX `fk_Payments_Players_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payments_Players`
    FOREIGN KEY (`player_id`)
    REFERENCES `nhn_academy_14`.`Players` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nhn_academy_14`.`Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhn_academy_14`.`Games` ;

CREATE TABLE IF NOT EXISTS `nhn_academy_14`.`Games` (
  `game_id` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `genre` VARCHAR(50) NOT NULL,
  `release_date` DATETIME NULL,
  PRIMARY KEY (`game_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nhn_academy_14`.`Scores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhn_academy_14`.`Scores` ;

CREATE TABLE IF NOT EXISTS `nhn_academy_14`.`Scores` (
  `score_id` INT NOT NULL,
  `play_history_id` INT NOT NULL,
  `score` INT NULL,
  `result` VARCHAR(45) NULL,
  `Scorescol` ENUM('WIN', 'LOSE', 'DRAW') NULL,
  PRIMARY KEY (`score_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nhn_academy_14`.`PlayHistories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhn_academy_14`.`PlayHistories` ;

CREATE TABLE IF NOT EXISTS `nhn_academy_14`.`PlayHistories` (
  `play_history_id` INT NOT NULL,
  `started_at` DATETIME NULL,
  `ended_at` DATETIME NULL,
  `player_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  `score_id` INT NOT NULL,
  PRIMARY KEY (`play_history_id`, `player_id`, `game_id`, `score_id`),
  INDEX `fk_PlayHistories_Players1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_PlayHistories_Games1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_PlayHistories_Scores1_idx` (`score_id` ASC) VISIBLE,
  CONSTRAINT `fk_PlayHistories_Players1`
    FOREIGN KEY (`player_id`)
    REFERENCES `nhn_academy_14`.`Players` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayHistories_Games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `nhn_academy_14`.`Games` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayHistories_Scores1`
    FOREIGN KEY (`score_id`)
    REFERENCES `nhn_academy_14`.`Scores` (`score_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
